version: "3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'singo.local -> http://singo:5000'
      STAGE: local
    volumes:
      - ./:/var/lib/https-portal
  singo:
    image: tockn/singo:latest
    ports:
      - 5000:5000
